colorScheme = "everblush"
defaultAppearance = "dark"

disableImageZoom = false

enableSearch = true
enableCodeCopy = true

mainSections = ["projects"]

[header]
  layout = "fixed-fill"

[homepage]
  layout = "hero"
  homepageImage = "hero"
  showRecent = true
  showRecentItems = 3
  cardView = true

[list]
  showHero = true
  showAuthor = true
  cardView = true
